### ISSUE TITLE
HTTPS

### ISSUE THREAD

**Issue by ByJIaT** [b2b-marketplace/b2b-marketplace-backend#136]
фронту нужен https

**Comment by Ivan-Skvortsov** [comment]
Булат, они на созвоне это просили? Для чего им https сейчас?

**Comment by ByJIaT** [comment]
> Булат, они на созвоне это просили? Для чего им https сейчас?

Да на созвоне, у них что-то не работает на http

**Comment by Ivan-Skvortsov** [comment]
Странно, а теперь просят http 😄 
Ну, в целом, в любом случае пришлось бы делать https, так что ок)
