### ISSUE TITLE
Страница с избранными товарами

### ISSUE THREAD

**Issue by ByJIaT** [b2b-marketplace/b2b-marketplace-backend#141]
Добавить страницу для вывода избранных товаров

**Comment by Ivan-Skvortsov** [comment]
А зачем?) У нас же уже есть эндпойнт `/products/` к которому мы можем обратиться с query параметром is_favorited и получить только избранные товары. Мне кажется, нет нужды в отдельном эндпойнте (странице).

Вообще, /products/ получается довольно универсальным:
 - для поиска товара просто передаем query параметр name (поиск по частичному совпадению)
 - для вывода товаров по категориям - параметр category или parent_category
 - и т.д.

**Comment by ByJIaT** [comment]
Согласен, забыл про фильтры)
