### ISSUE TITLE
Спецификацию поправить

### ISSUE THREAD

**Issue by esfiro4ka** [b2b-marketplace/b2b-marketplace-backend#43]
В связи с изменениями в моделях и коде проверить и поправить спецификацию по теме "пользователи"

**Comment by Ivan-Skvortsov** [comment]
Может быть, есть смысл начать генерировать спецификацию из кода?) Чтобы не тратить время на ручные правки.
Главное, фронтов вовремя оповещать, если что-то меняется

**Comment by esfiro4ka** [comment]
я плохо понимаю, как это работает. у нас же в коде не описаны некоторые темы, которые мы описали в спецификации специально, чтобы они были у фронта, и получится, что из кода будет неполная спецификация
